<a href="https://colab.research.google.com/github/19pa1a02a6/AI_lab/blob/master/experimemt_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# "EXPERIMENT-1:NUMPY"

1.numpy


a)different ways to create numpy arrays

In [ ]:
    import numpy as np
    a = np.array([1,2,3])
    print(a)

[1 2 3]


In [ ]:
a = np.array([[1,2,3],[98,99,100]])
print(a)

[[  1   2   3]
 [ 98  99 100]]


b)add , remove,modify elements in an array 

add:

In [ ]:
a = np.array([1,2,3])
b = np.append(a,[10,20,30])
print(b)

[ 1  2  3 10 20 30]


remove:

In [ ]:
c = np.delete(a,2)
print(c)

[1 2]


modify:

In [ ]:
c[c<5]=-1
print(c)

[-1 -1]


c)arithmetic operations on numpy arrays

In [ ]:
import numpy as np
a = ([1,2,3])
b = ([4,5,6])
num_sum = np.add(a,b)
num_diff = np.subtract(a,b)
num_quo = np.divide(a,b)
num_mod = np.mod(a,b)
num_pow = np.power(a,b)
print(num_sum)
print(num_diff)
print(num_quo)
print(num_mod)
print(num_pow)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[1 2 3]
[  1  32 729]


d)slicing and iterating of numpy arrays 

slicing:

In [ ]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:8])

[2 3 4 5 6 7 8]


iterating:

In [ ]:
for x in arr:
  print(x)

1
2
3
4
5
6
7
8
9
10


e)matrix operations on numpy arrays

In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
